import csv
import json
import re

FINDINGS = {
    # === From all 8 research batches — websites and emails found ===
    # Format: "normalized_name|normalized_town": {"website": "...", "email": "..."}

    # --- Batch 0: Ashland, Fort Fairfield, Mapleton, Mars Hill, Presque Isle (partial) ---
    "aroostook valley health center|ashland": {"website": "https://kvhc.org"},
    "ashland community center|ashland": {"website": "https://townofashland.org"},
    "ashland drug store|ashland": {"website": "https://citydrugrx.com"},
    "ashland family pharmacy|ashland": {"website": "https://citydrugrx.com"},
    "ashland health center|ashland": {"website": "https://kvhc.org"},
    "ashland historical society|ashland": {"website": "https://townofashland.org"},
    "ashland post office|ashland": {"website": "https://usps.com"},
    "ashland public library|ashland": {"website": "https://townofashland.org", "email": "library@townofashland.org"},
    "ashland recreation|ashland": {"website": "https://townofashland.org", "email": "macie.elwell@townofashland.org"},
    "ashland schools|ashland": {"website": "https://sad32.org"},
    "ashland town office|ashland": {"website": "https://townofashland.org"},
    "carquest auto parts|ashland": {"website": "https://carquest.com"},
    "daigle oil co|ashland": {"website": "https://daigleoil.com"},
    "family dollar|ashland": {"website": "https://familydollar.com"},
    "katahdin trust company|ashland": {"website": "https://katahdintrust.com"},
    "northeast pellets|ashland": {"website": "https://northeastpellets.net", "email": "northeastpellets@aol.com"},
    "prentiss carlisle|ashland": {"website": "https://prentissandcarlisle.com"},
    "stimsonouellette funeral home|ashland": {"website": "https://ouellettefuneralhome.com"},
    "usps ashland post office|ashland": {"website": "https://usps.com"},
    "boondocks grille|fort fairfield": {"website": "https://boondocksgrille.com", "email": "steve.boondocks@icloud.com"},
    "fields realty llc|fort fairfield": {"website": "https://fieldsrealtyllc.com"},
    "fort fairfield public library|fort fairfield": {"website": "https://fortfairfieldlibrary.org", "email": "library@fortfairfield.org"},
    "fort fairfield town office|fort fairfield": {"website": "https://fortfairfield.org"},
    "fort fairfield utilities district|fort fairfield": {"email": "ff.utilities@outlook.com"},
    "freshies fort fairfield|fort fairfield": {"website": "https://freshiesdeli.com"},
    "county bluegrass festival|fort fairfield": {"website": "http://countybluegrass.com", "email": "stev@countybluegrass.com"},
    "rite aid pharmacy|fort fairfield": {"website": "https://riteaid.com"},
    "the county federal credit union|fort fairfield": {"website": "https://countyfcu.org"},
    "mapleton oil co|mapleton": {"website": "https://mapletonoil.com", "email": "jessica@mapletonoil.com"},
    "mapleton post office|mapleton": {"website": "https://usps.com"},
    "usps mapleton post office|mapleton": {"website": "https://usps.com"},
    "big rock ski area|mars hill": {"website": "https://bigrockmaine.com"},
    "bigrock mountain|mars hill": {"website": "https://bigrockmaine.com"},
    "circle k on the run|mars hill": {"website": "https://circlek.com"},
    "family dollar|mars hill": {"website": "https://familydollar.com"},
    "pineland farms potato company inc|mars hill": {"website": "https://pinelandfarms.com"},
    "us post office mars hill|mars hill": {"website": "https://usps.com"},
    "ace hardware maine potato growers inc|presque isle": {"website": "https://acehardware.com"},
    "advance auto parts|presque isle": {"website": "https://advanceautoparts.com"},
    "arbys|presque isle": {"website": "https://arbys.com"},
    "aroostook county federal savings and loan|presque isle": {"website": "https://yourhomebank.com"},
    "aroostook mall|presque isle": {"website": "https://aroostookcentre.com"},

    # --- Batch 1: Presque Isle (continued), Washburn, Caribou (partial) ---
    "aroostook trusses inc|presque isle": {"website": "https://aroostooktrusses.com"},
    "autozone|presque isle": {"website": "https://autozone.com"},
    "big cheese pizza|presque isle": {"website": "https://bcpizza.wixsite.com/bigcheesepizza"},
    "bike board and ski|presque isle": {"website": "https://bikeboardandski.com"},
    "blueberry hill family campground|presque isle": {"website": "https://blueberryhillcampground.com"},
    "boston and maine room|presque isle": {"website": "https://bostonandmaineroom.com"},
    "bridgmans furniture|presque isle": {"website": "https://bridgmansfurniture.com"},
    "burger king|presque isle": {"website": "https://bk.com"},
    "carlsons auto body|presque isle": {"website": "https://carlsonsautobody.com"},
    "carols hope chest|presque isle": {"website": "https://carolshopecest.com"},
    "carrolls auto sales chevroletgmc|presque isle": {"website": "https://carrollsautosales.com", "email": "sales@carrollsautosales.com"},
    "central aroostook association|presque isle": {"website": "https://centralaroostookassociation.com"},
    "city pharmacy|presque isle": {"website": "https://citydrugrx.com"},
    "cityside milady salon|presque isle": {"website": "https://citysidemiladysalon.com"},
    "clukey electric|presque isle": {"website": "https://clukeyelectric.com"},
    "coatsworths jewelry|presque isle": {"website": "https://coatsworthsjewelry.com"},
    "currier memorials|presque isle": {"website": "https://curriermemorials.com"},
    "daigle oil co|presque isle": {"website": "https://daigleoil.com"},
    "dangelo insurance|presque isle": {"website": "https://dangeloinsurance.com"},
    "dennys of presque isle|presque isle": {"website": "https://dennys.com"},
    "dollar general|presque isle": {"website": "https://dollargeneral.com"},
    "dollar tree|presque isle": {"website": "https://dollartree.com"},
    "duncangraves funeral home|presque isle": {"website": "https://duncangraves.com"},
    "dunkin|presque isle": {"website": "https://dunkindonuts.com"},
    "family dollar|presque isle": {"website": "https://familydollar.com"},
    "giambattista law offices|presque isle": {"website": "https://giambattistalaw.com"},
    "graves shop n save|presque isle": {"email": "penny.leblanc@delhaize.com"},
    "hannaford supercenter|presque isle": {"website": "https://hannaford.com"},
    "hilton dodge chrysler jeep ram|presque isle": {"website": "https://hiltondodge.com"},
    "holiday inn express|presque isle": {"website": "https://ihg.com"},
    "houlton farms dairy|presque isle": {"website": "https://houltonfarmsdairy.com"},
    "ijr auto sales|presque isle": {"website": "https://ijrautosales.com"},
    "katahdin trust company|presque isle": {"website": "https://katahdintrust.com"},
    "kentucky fried chicken|presque isle": {"website": "https://kfc.com"},
    "lone pine brewery|presque isle": {"website": "https://lonepinebrewery.com"},
    "maine department of transportation|presque isle": {"website": "https://maine.gov"},
    "mandi martin photography|presque isle": {"website": "https://mandimartinphotography.com"},
    "mcdonalds|presque isle": {"website": "https://mcdonalds.com"},
    "mock family funeral home|presque isle": {"website": "https://mockfuneralhome.com"},
    "northern maine motors|presque isle": {"website": "https://northernmainemotors.com", "email": "ryan@northernmainemotors.com"},
    "northern maine savings bank|presque isle": {"website": "https://northernmainesavingsbank.com"},
    "pizza hut|presque isle": {"website": "https://pizzahut.com"},
    "presque isle animal hospital|presque isle": {"website": "https://piah.biz", "email": "piah@piah.biz"},
    "presque isle chamber of commerce|presque isle": {"website": "https://centralaroostookchamber.com"},
    "presque isle country club|presque isle": {"website": "https://presqueislecc.com"},
    "presque ise isle federal credit union": {"website": "https://presqueislefcu.com"},
    "presque isle honda suzuki kawasaki|presque isle": {"website": "https://presqueislemotorsports.com"},
    "presque isle humane society|presque isle": {"website": "https://presqueislehumanesociety.com"},
    "presque isle police department|presque isle": {"website": "https://presqueisle.org"},
    "presque isle post office|presque isle": {"website": "https://usps.com"},
    "presque ise isle public library": {"website": "https://presqueislelibrary.org"},
    "presque isle recreation department|presque isle": {"website": "https://presqueisle.org"},
    "presque isle sub shop|presque isle": {"website": "https://presqueislesubshop.com"},
    "presque isle town office|presque isle": {"website": "https://presqueisle.org"},
    "ramada by wyndham|presque isle": {"website": "https://wyndham.com"},
    "renee richards hair designs|presque isle": {"website": "https://reneerichardshair.com"},
    "rite aid|presque isle": {"website": "https://riteaid.com"},
    "sleep inn|presque isle": {"website": "https://choicehotels.com"},
    "subway|presque isle": {"website": "https://subway.com"},
    "the northeastland hotel|presque isle": {"website": "https://thenortheastlandhotel.com", "email": "rooms@thenortheastlandhotel.com"},
    "the viking restaurant|presque isle": {"website": "https://thevikingrestaurant.com"},
    "timmys supermarket|presque isle": {"website": "https://timmysmarket.com"},
    "usps presque isle post office|presque isle": {"website": "https://usps.com"},
    "walgreens|presque isle": {"website": "https://walgreens.com"},
    "walmart supercenter|presque isle": {"website": "https://walmart.com"},
    "washburn food mart|washburn": {"website": "https://countryfarmsmkt.com"},
    "washburn memorial public library|washburn": {"website": "https://washburnlibrary.com"},
    "washburn public library|washburn": {"website": "https://washburnlibrary.com"},
    "washburn recreation|washburn": {"website": "https://washburnmaine.org"},
    "washburn schools|washburn": {"website": "https://msad45.net"},
    "washburn town office|washburn": {"website": "https://washburnmaine.org"},
    "washburn post office|washburn": {"website": "https://usps.com"},

    # --- Batch 2: Caribou (continued) and Caribou/Limestone ---
    "advance auto parts|caribou": {"website": "https://advanceautoparts.com"},
    "aroostook savings loan|caribou": {"website": "https://yourhomebank.com", "email": "customerservice@yourhomebank.com"},
    "beaulieus garage body shop|caribou": {"website": "https://beaulieusgarageandbodyshop.com"},
    "best western caribou inn|caribou": {"website": "https://bestwestern.com", "email": "info@caribouinn.com"},
    "big cheese pizza caribou|caribou": {"website": "https://bcpizza.wixsite.com/bigcheesepizza"},
    "big cheese pizza|caribou": {"website": "https://bcpizza.wixsite.com/bigcheesepizza"},
    "burger boy|caribou": {"website": "https://burger-boy.com"},
    "burger king|caribou": {"website": "https://bk.com"},
    "carquest auto parts|caribou": {"website": "https://carquest.com"},
    "citgo|caribou": {"website": "https://citgo.com"},
    "caribou area chamber of commerce|caribou": {"website": "https://centralaroostookchamber.com", "email": "info@centralaroostookchamber.com"},
    "caribou country club|caribou": {"website": "https://caribougolf.com", "email": "proshop@caribougolf.com"},
    "caribou family medicine|caribou": {"website": "https://northernlighthealth.org"},
    "caribou fire department|caribou": {"website": "https://cariboumaine.org"},
    "caribou florist greenhouse|caribou": {"website": "https://noyesflowers.square.site"},
    "caribou ford lincoln|caribou": {"website": "https://griffethford.com"},
    "caribou inn convention center|caribou": {"website": "https://bestwestern.com", "email": "info@caribouinn.com"},
    "caribou parks recreation department|caribou": {"website": "https://cariboumaine.org"},
    "caribou pharmacy|caribou": {"website": "https://riteaid.com"},
    "caribou police department|caribou": {"website": "https://cariboumaine.org"},
    "caribou public library|caribou": {"website": "https://cariboumaine.org"},
    "caribou recreation department|caribou": {"website": "https://cariboumaine.org"},
    "caribou rehab nursing center|caribou": {"website": "https://caribourehab.com"},
    "caribou savealot|caribou": {"website": "https://savealot.com"},
    "caribou theater|caribou": {"website": "https://thecariboutheater.com", "email": "cariboutheatres@yahoo.com"},
    "caribou town office|caribou": {"website": "https://cariboumaine.org"},
    "cary medical center|caribou": {"website": "https://carymedicalcenter.org"},
    "circle k irving oil|caribou": {"website": "https://circlek.com"},
    "dollar general|caribou": {"website": "https://dollargeneral.com"},
    "dollar tree|caribou": {"website": "https://dollartree.com"},
    "dunkin|caribou": {"website": "https://dunkindonuts.com"},
    "family dollar|caribou": {"website": "https://familydollar.com"},
    "gills point s tire auto|caribou": {"website": "https://gillspointstire.com"},
    "greenhouse restaurant|caribou": {"website": "https://bestwestern.com", "email": "info@caribouinn.com"},
    "griffeth ford|caribou": {"website": "https://griffethford.com"},
    "hannaford supermarket pharmacy|caribou": {"website": "https://hannaford.com"},
    "katahdin trust company|caribou": {"website": "https://katahdintrust.com", "email": "customerservice@katahdintrust.com"},
    "keybank|caribou": {"website": "https://key.com"},
    "lancastermorgan funeral home|caribou": {"website": "https://lancastermorgan.com"},
    "machias savings bank|caribou": {"website": "https://machiassavings.bank"},
    "maine veterans homes caribou|caribou": {"website": "https://maineveteranshomes.org"},
    "mcdonalds|caribou": {"website": "https://mcdonalds.com"},
    "mobil on the run|caribou": {"website": "https://mobil.com"},
    "northern light primary care caribou|caribou": {"website": "https://northernlighthealth.org"},
    "northern light walkin care caribou|caribou": {"website": "https://northernlighthealth.org"},
    "northern maine dental|caribou": {"website": "https://nmgeneral.org"},
    "northern maine general|caribou": {"website": "https://nmgeneral.org"},
    "noyes flower plant shoppe|caribou": {"website": "https://noyesflowers.square.site"},
    "noyes flower and plant shoppe|caribou": {"website": "https://noyesflowers.square.site"},
    "nylander museum|caribou": {"website": "https://nylandermuseum.com", "email": "nylandermuseum@gmail.com"},
    "old iron inn bed breakfast|caribou": {"website": "https://oldironinn.com", "email": "kateandkevin@oldironinn.com"},
    "on the run|caribou": {"website": "https://mobil.com"},
    "pines health services caribou health center|caribou": {"website": "https://pineshealth.org"},
    "pines health services caribou|caribou": {"website": "https://pineshealth.org"},
    "pizza hut|caribou": {"website": "https://pizzahut.com"},
    "rite aid walgreens pharmacy|caribou": {"website": "https://riteaid.com"},
    "ruska coffee co|caribou": {"website": "https://ruskacoffee.com"},
    "sw collins co|caribou": {"website": "https://swcollins.com", "email": "marketing@swcollins.com"},
    "savealot|caribou": {"website": "https://savealot.com"},
    "sean duplessie state farm insurance|caribou": {"website": "https://statefarm.com"},
    "shell|caribou": {"website": "https://shell.com"},
    "sherwinwilliams paint store|caribou": {"website": "https://sherwin-williams.com"},
    "sleepers market|caribou": {"website": "https://sleepersmarket.com"},
    "subway|caribou": {"website": "https://subway.com"},
    "td bank|caribou": {"website": "https://td.com"},
    "the caribou theater|caribou": {"email": "cariboutheatres@yahoo.com"},
    "tim hortons|caribou": {"website": "https://timhortons.com"},
    "us post office caribou|caribou": {"website": "https://usps.com"},
    "aroostook national wildlife refuge|limestone": {"website": "https://fws.gov/refuge/aroostook"},
    "dfas|limestone": {"website": "https://dfas.mil"},
    "dollar general|limestone": {"website": "https://dollargeneral.com"},
    "limestone post office|limestone": {"website": "https://usps.com"},
    "loring commerce centre|limestone": {"website": "https://loring.org"},
    "loring development authority|limestone": {"website": "https://loring.org", "email": "LDA@Loring.org"},
    "loring job corps|limestone": {"website": "https://jobcorps.gov"},
    "loring job corps center|limestone": {"website": "https://jobcorps.gov"},
    "maine school of science and mathematics|limestone": {"website": "https://mssm.org", "email": "admissions@mssm.org"},
    "mikes family market|limestone": {"website": "https://mikesfamilymarket.com", "email": "info@aroostookonline.com"},
    "new england kenworth|limestone": {"website": "https://kenworth.com"},
    "pines health services loring health center|limestone": {"website": "https://pineshealth.org"},
    "pines loring health center|limestone": {"website": "https://pineshealth.org"},
    "sfe manufacturing|limestone": {"website": "https://sfemanufacturing.com"},
    "sfe manufacturing inc|limestone": {"website": "https://sfemanufacturing.com"},
    "us post office limestone|limestone": {"website": "https://usps.com"},
    "katahdin trust co|limestone": {"website": "https://katahdintrust.com", "email": "customerservice@katahdintrust.com"},
    "limestone community school|limestone": {"email": "blothrop@lcseagles.org"},

    # --- Batch 3: Bridgewater, Hodgdon, Houlton (continued) ---
    "9 lake outfitters|bridgewater": {"email": "email@9lakeoutfitters.com"},
    "bradbury barrel company|bridgewater": {"website": "https://bradburybarrel.com", "email": "info@bradburybarrel.com"},
    "bridgewater mainway circle k fosters bridgewater|bridgewater": {"website": "https://circlek.com"},
    "j j cedar mill|bridgewater": {"email": "info@jjcedarmill.com"},
    "rh foster fosters bridgewater|bridgewater": {"website": "https://rhfoster.com"},
    "crown of maine taxidermy|hodgdon": {"website": "https://crownofmainetaxidermy.com"},
    "forticor farms|hodgdon": {"email": "info@forticorfarms.com"},
    "hidden spring winery|hodgdon": {"email": "hiddenspring@mail.com"},
    "pleasant view tree farm|hodgdon": {"website": "https://pleasantviewtreefarm.com", "email": "robertmulvey@ainop.com"},
    "acap aroostook county action program|houlton": {"website": "https://acap-me.org", "email": "info@acap-me.org"},
    "advance auto parts|houlton": {"website": "https://advanceautoparts.com"},
    "bangor savings bank|houlton": {"website": "https://bangor.com", "email": "bangorsupport@bangor.com"},
    "cary library|houlton": {"website": "https://cary.lib.me.us", "email": "cary@cary.lib.me.us"},
    "chadwick florist greenhouses|houlton": {"website": "https://mechadwickflorist.com"},
    "circle k|houlton": {"website": "https://circlek.com"},
    "daigle oil co|houlton": {"website": "https://daigleoil.com", "email": "info@daigleoil.com"},
    "dead river company|houlton": {"website": "https://deadriver.com"},
    "dollar tree|houlton": {"website": "https://dollartree.com"},
    "duff service station|houlton": {"email": "duffsservice@gmail.com"},
    "eastern maine electric coop|houlton": {"website": "https://emec.com"},
    "family dollar|houlton": {"website": "https://familydollar.com"},
    "greater houlton christian academy|houlton": {"website": "https://ghca.com", "email": "office@ghca.com"},
    "hannaford supermarket|houlton": {"website": "https://hannaford.com"},
    "hidden spring winery|houlton": {"email": "hiddenspring@mail.com"},
    "houlton community golf club|houlton": {"email": "houltongolf@gmail.com"},
    "houlton regional hospital|houlton": {"website": "https://mainehealth.org/houlton-regional-hospital", "email": "info@houltonregional.org"},
    "houlton water company|houlton": {"website": "https://hwco.org", "email": "sherman@hwco.org"},
    "katahdin trust co|houlton": {"website": "https://katahdintrust.com", "email": "customerservice@katahdintrust.com"},
    "louisiana pacific|houlton": {"website": "https://lpcorp.com"},
    "machias savings bank|houlton": {"website": "https://machiasbank.com"},
    "mardens|houlton": {"website": "https://mardens.com"},
    "napa coastal auto parts|houlton": {"website": "https://napaonline.com"},
    "pioneer broadband|houlton": {"website": "https://pioneerbroadband.net", "email": "sales@pioneerbroadband.net"},
    "sw collins|houlton": {"website": "https://swcollins.com"},
    "sherwin williams|houlton": {"website": "https://sherwin-williams.com"},
    "shiretown inn and suites|houlton": {"website": "https://shiretowninnandsuites.com", "email": "info@shiretowninnandsuites.com"},
    "state farm insurance|houlton": {"website": "https://statefarm.com"},
    "tate lyle|houlton": {"website": "https://tateandlyle.com"},
    "temple theater|houlton": {"website": "https://templehoulton.com", "email": "movies@templehoulton.com"},
    "walmart 1974|houlton": {"website": "https://walmart.com"},
    "ward cedar log homes|houlton": {"website": "https://wardcedarloghomes.com", "email": "info@wardcedarloghomes.com"},
    "birch point campground cottages|island falls": {"website": "https://birchpointcampground.com", "email": "edpoint@pivot.net"},
    "daigle oil co island falls|island falls": {"website": "https://daigleoil.com"},
    "island falls animal health clinic|island falls": {"email": "IFAHC@protonmail.com"},
    "jerrys food store jerrys thriftway|island falls": {"email": "jerrysfoodstore848@hotmail.com"},
    "katahdin federal credit union|island falls": {"website": "https://katahdinfcu.org", "email": "info@katahdinfcu.org"},
    "katahdin trust company|island falls": {"website": "https://katahdintrust.com"},
    "houlton community golf course|new limerick": {"website": "https://houltongolf.com", "email": "houltongolf@gmail.com"},
    "aroostook auto tech|houlton": {"email": "aag@gwi.net"},

    # --- Batch 4: Houlton area (continued from Cary Library through Porter's Garage) ---
    "fa peabody|houlton": {"website": "https://fapeabody.com"},
    "harbison plumbing heating|houlton": {"email": "info@hphac.com"},
    "county micro inc|houlton": {"email": "hello@countymicro.com"},

    # --- Batch 5: Island Falls through Millinocket ---
    "sewall house yoga retreat|island falls": {"website": "https://sewallhouse.com"},
    "vajowa golf course|island falls": {"website": "https://vajowa-golf-course.com"},
    "aurora mills and farm|linneus": {"website": "https://auroramillsandfarm.com", "email": "auroramills@pwless.net"},
    "clarks auto sales|linneus": {"website": "https://clarksautosaleshoulton.com"},
    "county home improvements|linneus": {"website": "https://countyhome-improvements.com"},
    "hagan farms|linneus": {"email": "haganfarms@gmail.com"},
    "katahdins shadow outfitters|linneus": {"website": "https://huntkso.com", "email": "Info@HuntKSO.com"},
    "natures circle farm|linneus": {"website": "https://naturescirclefarm.com", "email": "megscott1@live.com"},
    "sunnyside family farm|linneus": {"website": "https://sunnysidefamilyfarm.com", "email": "fermeensoleillee.sunnysidefarm@gmail.com"},
    "golding construction|littleton": {"website": "https://goldingconstruction.com"},
    "houlton band of maliseet indians|littleton": {"website": "https://maliseets.net"},
    "perrin realty inc|littleton": {"website": "https://perrinrealty.com"},
    "shady ridge disc golf|littleton": {"website": "https://shadyridgediscgolf.com", "email": "ShadyRidge@pm.me"},
    "southern aroostook agricultural museum|littleton": {"website": "https://southernaroostookagriculturalmuseum.org", "email": "southernaroostookagmuseum@gmail.com"},
    "houlton community golf course|new limerick": {"website": "https://houltongolf.com", "email": "houltongolf@gmail.com"},
    "natures circle farm|new limerick": {"website": "https://naturescirclefarm.com", "email": "megscott1@live.com"},
    "tall timber lodge|new limerick": {"website": "https://thetalltimberlodge.com"},
    "arborwall solid cedar homes|oakfield": {"website": "https://arborwall.com"},
    "katahdin cedar log homes katahdin forest products|oakfield": {"website": "https://katahdincedarloghomes.com"},
    "katahdin trust company|oakfield": {"website": "https://katahdintrust.com"},
    "brookside inn|smyrna": {"website": "https://thebrooksideinn.com"},
    "spring break maple honey|smyrna": {"website": "https://mainemapleandhoney.com", "email": "info@mainemapleandhoney.com"},
    "crandalls hardware|east millinocket": {"website": "https://crandallshardware.com"},
    "eastmill federal credit union|east millinocket": {"website": "https://eastmillfcu.org"},
    "family dollar|east millinocket": {"website": "https://familydollar.com"},
    "napa auto parts|east millinocket": {"website": "https://napaonline.com"},
    "katahdin shadows campground|medway": {"website": "https://katahdinshadows.com", "email": "katshadcamp@midmaine.com"},
    "two rivers canoe tackle|medway": {"website": "https://tworiverscanoe.com", "email": "bigcanoe@midmaine.com"},
    "advance auto parts|millinocket": {"website": "https://advanceautoparts.com"},
    "appalachian trail lodge|millinocket": {"website": "https://appalachiantrailhostel.com", "email": "info@appalachiantrailhostel.com"},
    "bangor savings bank|millinocket": {"website": "https://bangor.com"},
    "baxter park inn|millinocket": {"website": "https://baxterparkinn.com", "email": "stay@baxterparkinn.com"},
    "dead river co|millinocket": {"website": "https://deadriver.com"},
    "dunkin donuts|millinocket": {"website": "https://dunkindonuts.com"},
    "family dollar store|millinocket": {"website": "https://familydollar.com"},
    "gather inn|millinocket": {"website": "https://gatherinnmaine.com", "email": "gatherinn.me@gmail.com"},
    "hang wong restaurant|millinocket": {"website": "https://hangwongchinese.com"},
    "hannaford supermarket pharmacy|millinocket": {"website": "https://hannaford.com"},
    "hillcrest golf club|millinocket": {"website": "https://hillcrestgolfme.com", "email": "golfhillcrest@hotmail.com"},
    "hotel terrace restaurant|millinocket": {"website": "https://hotelterracemillinocket.us"},
    "ice fish inn|millinocket": {"website": "https://icefishinn.com"},
    "katahdin chamber of commerce|millinocket": {"website": "https://katahdinmaine.com", "email": "members@katahdinmaine.com"},
    "katahdin federal credit union|millinocket": {"website": "https://katahdinfcu.org", "email": "info@katahdinfcu.org"},
    "katahdin general store|millinocket": {"website": "https://katahdingeneral.com"},
    "katahdin inn suites|millinocket": {"website": "https://katahdininnandsuites.com"},
    "katahdin motors chevrolet cadillac|millinocket": {"website": "https://katahdinmotors.com"},
    "katahdin valley health center|millinocket": {"website": "https://kvhc.org"},
    "knife edge trading post|millinocket": {"website": "https://knifeedgetrading.com"},
    "lamson funeral home|millinocket": {"website": "https://lamsonfh.com", "email": "chiplamson@lamsonfh.com"},
    "life style fitness center|millinocket": {"email": "wellness@mrhme.org"},
    "magic city real estate|millinocket": {"email": "magiccityrealestate@outlook.com"},
    "memories of maine gallery|millinocket": {"website": "https://memoriesofmaine.com"},
    "millinocket floral shop|millinocket": {"website": "https://millinocketfloralandgift.com"},
    "millinocket memorial library|millinocket": {"website": "https://millinocketlib.org", "email": "info@millinocketlib.org"},
    "millinocket regional hospital|millinocket": {"website": "https://mrhme.org", "email": "info@mrhme.org"},
    "new england outdoor center|millinocket": {"website": "https://neoc.com", "email": "info@neoc.com"},
    "river drivers restaurant|millinocket": {"website": "https://neoc.com"},
    "subway|millinocket": {"website": "https://subway.com"},

    # --- Batch 6: Millinocket, Patten, Sherman, Shin Pond, Burlington, Enfield ---
    "hair razor|millinocket": {"website": "https://hairrazor.net"},
    "mcdonalds|millinocket": {"website": "https://mcdonalds.com"},
    "millinocket house of pizza|millinocket": {"website": "https://mhppizza.com"},
    "north woods real estate|millinocket": {"website": "https://northwoodsrealestate.com"},
    "preble oil co|millinocket": {"website": "https://prebleoil.com"},
    "rivers edge motel pizza|medway": {"website": "https://riversedgemotel.com"},
    "napa auto parts|east millinocket": {"website": "https://napaonline.com"},
    "ellis family market|east millinocket": {"email": "peter.ellis@hannaford.com"},
    "conklins lodge camps|patten": {"website": "https://conklinslodge.com", "email": "guideonemaine@yahoo.com"},
    "dollar general|patten": {"website": "https://dollargeneral.com"},
    "ellis family market|patten": {"email": "joellis@hannaford.com"},
    "katahdin trust company|patten": {"website": "https://katahdintrust.com"},
    "katahdin valley motel|sherman": {"website": "https://katahdinvalleymotel.com", "email": "info@katahdinvalleymotel.com"},
    "salted butter farm|sherman": {"website": "https://saltedbutterfarm.com"},
    "sherman thriftway|sherman": {"website": "https://shermanthriftway.com"},
    "barnes brook golf course|enfield": {"website": "https://barnesbrookgolf.com"},
    "dollar general|enfield": {"website": "https://dollargeneral.com"},
    "hammond lumber company|enfield": {"website": "https://hammondlumber.com"},
    "pleasant river lumber company|enfield": {"website": "https://pleasantriverlumber.com", "email": "info@pleasantriverlumber.com"},

    # --- Batch 7: Lincoln area ---
    "bangor savings bank|howland": {"website": "https://bangor.com", "email": "bangorsupport@bangor.com"},
    "howlandenfield federal credit union|howland": {"website": "https://howlandenfieldfcu.com", "email": "info@howlandenfieldfcu.com"},
    "marble creek acres winery cidery|lee": {"website": "https://marblecreekacres.com", "email": "mainecellars@gmail.com"},
    "bangor savings bank|lincoln": {"website": "https://bangor.com", "email": "bangorsupport@bangor.com"},
    "barker business services|lincoln": {"website": "https://barkertax.com", "email": "taxman2@barkertax.com"},
    "big apple store|lincoln": {"website": "https://bigapplestores.com"},
    "blazin trailz|lincoln": {"website": "https://blazintrailz.com"},
    "clay funeral home|lincoln": {"website": "https://clayfuneralhome.com"},
    "dead river company|lincoln": {"website": "https://deadriver.com"},
    "dollar tree|lincoln": {"website": "https://dollartree.com"},
    "dubay auto parts napa|lincoln": {"website": "https://napaonline.com"},
    "hr block|lincoln": {"website": "https://hrblock.com"},
    "hannaford supermarket|lincoln": {"website": "https://hannaford.com"},
    "health access network boreas family medicine|lincoln": {"website": "https://healthaccessnetwork.org", "email": "info@healthaccessnetwork.org"},
    "keybank|lincoln": {"website": "https://key.com"},
    "lincoln news|lincoln": {"website": "https://lincnews.com", "email": "news@lincnews.com"},
    "lincoln regional veterinary hospital|lincoln": {"email": "lrvhinfo@gmail.com"},
    "machias savings bank|lincoln": {"website": "https://machiasbank.com"},
    "mardens surplus salvage|lincoln": {"website": "https://mardens.com"},
    "pelletier ford of lincoln|lincoln": {"website": "https://pelletierford.com"},
    "penobscot valley hospital|lincoln": {"website": "https://pvhme.org", "email": "info@pvhme.org"},
    "rh foster energy|lincoln": {"website": "https://rhfoster.com", "email": "info@rhfoster.com"},
    "town of lincoln|lincoln": {"website": "https://lincolnmaine.org", "email": "awoodard@lincolnmaine.org"},
    "true value|lincoln": {"website": "https://truevalue.com"},
    "walmart supercenter|lincoln": {"website": "https://walmart.com"},
    "big apple store|mattawamkeag": {"website": "https://bigapplestores.com"},
    "wheeler world|mattawamkeag": {"email": "25194@powersportshub.com"},
    "ellis family market|east millinocket": {"email": "peter.ellis@hannaford.com"},

    # === Additional from EMAIL_UPDATES that may not be above ===
    "sw collins co|presque isle": {"website": "https://swcollins.com", "email": "marketing@swcollins.com"},
    "hampton inn presque isle|presque isle": {"email": "PQIMA_hampton@hilton.com"},
    "gram russos italian restaurant|presque isle": {"email": "cicc3733@aol.com"},
    "caribou eye care pa|caribou": {"email": "jillian@cariboueyecare.com"},
    "county sports inc|caribou": {"email": "countysports1@maine.rr.com"},
    "highway tire inc|caribou": {"email": "highwaytire@myfairpoint.net"},
    "monicas scandinavian imports|caribou": {"email": "monicasimports@myfairpoint.net"},
    "plourde furniture co|caribou": {"email": "katie@plourdefurniturecompany.com"},
    "priority tractor equipment|caribou": {"email": "sales@prioritytractor.com"},
    "plisga day surveys|linneus": {"website": "https://wemapit.com"},
    "arborwall solid cedar homes|oakfield": {"website": "https://arborwall.com"},
    "katahdin valley health center island falls|island falls": {"website": "https://kvhc.org"},
    "fa peabody insurance|lincoln": {"website": "https://fapeabody.com"},
    "sw collins co doitbest|lincoln": {"website": "https://swcollins.com"},
    "pleasant river lumber company|enfield": {"website": "https://pleasantriverlumber.com", "email": "info@pleasantriverlumber.com"},
}

def normalize(s):
    s = s.lower().strip()
    s = re.sub(r'[^a-z0-9\s]', '', s)
    s = re.sub(r'\s+', ' ', s)
    return s.strip()

def make_key(name, town):
    return f"{normalize(name)}|{normalize(town)}"

def main():
    regions = ['presque_isle_area', 'houlton_region', 'millinocket_area', 'lincoln_area']
    total_ws = 0
    total_em = 0

    for region in regions:
        fp = f'cleaned/{region}.csv'
        with open(fp, newline='', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            rows = list(reader)
            fieldnames = reader.fieldnames

        updated_ws = 0
        updated_em = 0
        for row in rows:
            key = make_key(row['Business Name'], row.get('Town', ''))
            if key in FINDINGS:
                fdata = FINDINGS[key]
                if fdata.get('website') and not row.get('Website', '').strip():
                    row['Website'] = fdata['website']
                    updated_ws += 1
                if fdata.get('email') and not row.get('Email', '').strip():
                    row['Email'] = fdata['email']
                    updated_em += 1

        if updated_ws or updated_em:
            with open(fp, 'w', newline='', encoding='utf-8') as f:
                writer = csv.DictWriter(f, fieldnames=fieldnames)
                writer.writeheader()
                writer.writerows(rows)

        total_ws += updated_ws
        total_em += updated_em
        print(f'{region}: +{updated_ws} websites, +{updated_em} emails')

    print(f'\nTotal: +{total_ws} websites, +{total_em} emails')

if __name__ == '__main__':
    main()
