import json, urllib.request, urllib.parse, re, time, socket
socket.setdefaulttimeout(5)

# Read the imprecise entries from report
entries = []
with open('regeocode_report.txt') as f:
    lines = f.readlines()

# Parse entries from the report (lines after "STILL IMPRECISE ENTRIES")
in_list = False
for line in lines:
    if 'STILL IMPRECISE ENTRIES' in line:
        in_list = True
        continue
    if 'NOTE: Precision audit' in line or 'Generated by' in line:
        in_list = False
        continue
    if not in_list or not line.strip():
        continue
    
    # Parse: "   Business Name | Address | current=(lat, lng)"
    m = re.match(r'\s+(.+?)\s+\|\s+(.+?)\s+\|\s+current=\(([\d.-]+),\s*([\d.-]+)\)', line)
    if m:
        name = m.group(1).strip()
        address = m.group(2).strip()
        lat = float(m.group(3))
        lng = float(m.group(4))
        entries.append({'name': name, 'address': address, 'lat': lat, 'lng': lng})

print(f'Loaded {len(entries)} entries from report')

# Also load current coordinates
with open('coordinates.json') as f:
    coords = json.load(f)

# Build a lookup from business name to key
with open('cleaned/all_businesses.json') as f:
    all_biz = json.load(f)

name_to_key = {}
for b in all_biz:
    name_to_key[b['name'].lower().strip()] = b['key']

def census_geocode(address):
    url = 'https://geocoding.geo.census.gov/geocoder/geographies/onelineaddress?' + urllib.parse.urlencode({
        'address': address,
        'benchmark': 'Public_AR_Current',
        'vintage': 'Current_Current',
        'format': 'json',
    })
    try:
        with urllib.request.urlopen(url) as resp:
            data = json.loads(resp.read().decode())
            matches = data.get('result', {}).get('addressMatches', [])
            if matches:
                m = matches[0]
                return (m['coordinates']['y'], m['coordinates']['x'], m.get('matchedAddress', ''))
    except:
        pass
    return None

improved = 0
failed = 0
for i, entry in enumerate(entries):
    addr = entry['address']
    name = entry['name']
    
    # Clean up address for Census API
    # Remove any trailing parenthetical
    addr_clean = re.sub(r'\s*\(.*?\)\s*$', '', addr).strip()
    # Remove "PO Box" entries
    if 'PO Box' in addr_clean or 'P.O.' in addr_clean:
        failed += 1
        continue
    
    # Build Census query - format: "Street, City, ST ZIP"
    # The address is usually "Street, City" already
    census_addr = addr_clean
    
    result = census_geocode(census_addr)
    if result:
        new_lat, new_lng, matched = result
        old_lat, old_lng = entry['lat'], entry['lng']
        
        # Only update if coordinates significantly differ
        if abs(new_lat - old_lat) > 0.0001 or abs(new_lng - old_lng) > 0.0001:
            # Find the key
            key = name_to_key.get(name.lower().strip())
            if key and key in coords:
                coords[key] = {'lat': new_lat, 'lng': new_lng}
                improved += 1
                if improved <= 3 or improved % 50 == 0:
                    print(f'  ✅ [{improved}] {name[:40]:40s} ({old_lat:.4f},{old_lng:.4f}) → ({new_lat:.4f},{new_lng:.4f})')
    
    time.sleep(0.2)  # Rate limit: 5 req/s

# Save updated coordinates
with open('coordinates.json', 'w') as f:
    json.dump(coords, f, indent=2)

print(f'\n✅ Census geocode complete: {improved} improved, {failed} skipped (PO box/no match)')
